language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t jzhao5/docker-react2 -f Dockerfile.dev .

script:
  - docker run -e CI=true jzhao5/docker-react2 npm run test
deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react2"
    env: "DockerReact2-env"
    bucket_name: "myapp-demo-2020"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY