version: 0.2
phases:
  
  install:
    runtime-versions:
      docker: 19

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI_1=149083378091.dkr.ecr.us-east-1.amazonaws.com/multi-client
      - REPOSITORY_URI_2=149083378091.dkr.ecr.us-east-1.amazonaws.com/multi-nginx
      - REPOSITORY_URI_3=149083378091.dkr.ecr.us-east-1.amazonaws.com/multi-server
      - REPOSITORY_URI_4=149083378091.dkr.ecr.us-east-1.amazonaws.com/multi-worker
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t multi-docker -f ./client/Dockerfile.dev ./client
      - docker run -e CI=true multi-docker npm run test
      
       
  post_build:
    commands:
        - echo Build completed on `date`
        - echo Pushing the Docker images...
        - echo $CODEBUILD_SRC_DIR
        - docker build -t $REPOSITORY_URI_1:latest ./client
        - docker tag $REPOSITORY_URI_1:latest $REPOSITORY_URI_1:$IMAGE_TAG
        - docker push $REPOSITORY_URI_1:latest
        - docker push $REPOSITORY_URI_1:$IMAGE_TAG
        - docker build -t $REPOSITORY_URI_2:latest ./nginx
        - docker tag $REPOSITORY_URI_2:latest $REPOSITORY_URI_2:$IMAGE_TAG
        - docker push $REPOSITORY_URI_2:latest
        - docker push $REPOSITORY_URI_2:$IMAGE_TAG
        - docker build -t $REPOSITORY_URI_3:latest ./server
        - docker tag $REPOSITORY_URI_3:latest $REPOSITORY_URI_3:$IMAGE_TAG
        - docker push $REPOSITORY_URI_3:latest
        - docker push $REPOSITORY_URI_3:$IMAGE_TAG
        - docker build -t $REPOSITORY_URI_4 ./worker
        - docker tag $REPOSITORY_URI_4:latest $REPOSITORY_URI_4:$IMAGE_TAG
        - docker push $REPOSITORY_URI_4:latest
        - docker push $REPOSITORY_URI_4:$IMAGE_TAG